# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abb5999f78f79cbbfc544a2e4b146bf55f6cbff9a160655b44ba9f24165f6eecb637dc3614bfa513d8ff28bf9e85f934c343f8d18aaac21a610841bd88c3630d

test:
  secret_key_base: c7cb8076c8b2fd7843338a71db2386b2074079b63df2bb4feca23b3752f623df80fe0fd0cb5a5dbeff591ab1cfa1fc39a5139d61caa5dac3b22d98a2fcf8b604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
